version: "2"
services:
  wordpress:
    image: wordpress:latest
#    image: wordpress:php7.0-fpm-alpine
#    build: ./template
    container_name: corporate
    ports:
      - "8880:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    networks:
      - flat-network
    env_file: .env
    volumes:
      - ./themes/layerswp:/var/www/html/wp-content/themes/layerswp
      - plugins:/var/www/html/wp-content/plugins
      - ./php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - flat-network
    env_file: .env
volumes:
  db-data:
  plugins:
networks:
  flat-network:
#  default:
#    external:
#       name: nginxproxy_default
